### ISSUE TITLE
change your setup directory name for setup linux

### ISSUE THREAD

**Issue by moodiabdoul** [JBossOutreach/blog.jbossoutreach.org#144]
i think if biginner like me view this name setup-linux they think that you want setup a liunix distrib
but i want you change directory to setup-for-linux  sorry for my bad english
![screenshot_2018-11-10 jbossoutreach blog jbossoutreach org](https://user-images.githubusercontent.com/44871128/48300414-45843e00-e4dd-11e8-9d44-fa7bee379a21.png)

**Comment by nikitadhiman** [comment]
What exactly is the issue here?

**Comment by moodiabdoul** [comment]
i wanted you change setup-linux to setup-for-linux i thinked that is an issue

**Comment by nikitadhiman** [comment]
File name would ideally not be considered as an issue, just in case it misguides user then it's a valid point. I'm assuming when one sees setup-linux and setup-for-linux one would assume the same thing that this document instructs how to make project setup on Linux machine. Correct me if I'm wrong or in case I'm missing something

**Comment by moodiabdoul** [comment]
ok thanks  i am agree with you
